### ISSUE TITLE
Remove double 14 scaling

### ISSUE THREAD

**Issue by jthorton** [openforcefield/smirnoff-plugins#51]
Due to an issue with ForceBalance not checking for global parameters in`CustomBondForces` we had to add the `scale14` global parameter to the `CustomNonbondedForce` to allow fitting of the scale factor. This is now fixed in [ForceBalance](https://github.com/leeping/forcebalance/pull/263) and the [fix](https://github.com/openforcefield/smirnoff-plugins/pull/37) can be removed from here once this package works with `openff-toolkit>0.11` and `openff-interchange` as these are the only versions now compatible with `ForceBalance`.

**Comment by mattwthompson** [comment]
I'm was a little confused by this but just writing up my questions clarified it, I think.

If I understand correctly
* the 1-4 scaling factor is not at risk of being applied twice
* the issue is that it shows up in two places (`.scale14` `.global_parameters`).
* the linked change was just so ForceBalance would be aware of it as a tunable parameter, which is previously missed because of the types of forces it was looking at, and nothing to do with which force it was applied to

I also assume you want it to
* remain as a tunable parameter on the `ParameterHandler`/OFFXML blob long-term
* only shows up on the `CustomBondForce` that is used for 1-4 interactions
* not touch the `CustomNonbondedForce` since there would be no point

**Comment by jthorton** [comment]
Yes to all!
